# Generated by Django 5.2.8 on 2025-11-25 04:24

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_files', '0004_historicaldocumentfile_historicalimagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('start_at', models.DateTimeField(verbose_name='Start at')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='End at')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('location_text', models.CharField(blank=True, help_text='Free text location. TODO: replace with Place relation when available.', max_length=255, verbose_name='Location (text)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('attachments', models.ManyToManyField(blank=True, help_text='Document attachments linked to this event.', related_name='attached_to_events', to='media_files.documentfile', verbose_name='Attachments')),
                ('featured_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_events', to='media_files.imagefile', verbose_name='Featured media')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('start_at', 'id'),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Translation',
                'db_table': 'events_event_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
