# Generated by Django 5.2.8 on 2025-11-26 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for this event (defaults to Events category)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='event',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per'),
        ),
        migrations.AddField(
            model_name='event',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació'),
        ),
        migrations.AddField(
            model_name='event',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació'),
        ),
        migrations.AddField(
            model_name='event',
            name='metadescripcion',
            field=models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció'),
        ),
        migrations.AddField(
            model_name='event',
            name='metatitulo',
            field=models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol'),
        ),
        migrations.AddField(
            model_name='event',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='Identificador únic per a URLs', max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='EventCategorySingleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(help_text='The root category for all events', on_delete=django.db.models.deletion.PROTECT, related_name='event_singleton', to='core.category', verbose_name='Events Category')),
            ],
            options={
                'verbose_name': 'Events Category Configuration',
            },
        ),
    ]
