# Generated by Django 5.2.8 on 2025-12-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_category_parent"),
        ("events", "0002_integrate_with_core"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtranslation",
            name="summary",
            field=models.CharField(blank=True, default="", max_length=280, verbose_name="Summary"),
        ),
        migrations.AddField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Is featured"),
        ),
        migrations.AddField(
            model_name="event",
            name="is_free",
            field=models.BooleanField(default=True, verbose_name="Is free"),
        ),
        migrations.AddField(
            model_name="event",
            name="price_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional display price (e.g. '10 €', 'Free entry').",
                max_length=120,
                verbose_name="Price text",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags linked to this event.",
                related_name="events",
                to="core.tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="venue_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the venue or organizer (free text).",
                max_length=200,
                verbose_name="Venue name",
            ),
        ),
    ]

