"""Migration for event points value."""
# Generated by Django 5.2.8 on 2026-01-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_fields_and_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="points_value",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Points awarded for event check-in.",
                verbose_name="Points value",
            ),
        ),
    ]
