# Generated by Django 5.2.8 on 2026-01-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_userfavoriteevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional price for the event (indicative).', max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
