# Generated by Django 5.2.8 on 2026-01-26 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_price_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent event if this is part of a recurrence series.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='events.event', verbose_name='Parent Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end_date',
            field=models.DateTimeField(blank=True, help_text='Date until which the event recurs.', null=True, verbose_name='Recurrence End Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.CharField(blank=True, help_text='RRULE string for recurrent events (e.g. FREQ=WEEKLY;BYDAY=MO).', max_length=255, null=True, verbose_name='Recurrence Rule'),
        ),
    ]
