# Generated by Django 5.2.8 on 2026-01-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_recurrence_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence_end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence_rule',
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Start at')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='End at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Date',
                'verbose_name_plural': 'Event Dates',
                'ordering': ('start_at',),
            },
        ),
    ]
