# Generated by Django 5.2.8 on 2026-01-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_refactor_event_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start at'),
        ),
    ]
