# Generated by Django 5.2.8 on 2026-02-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_make_dates_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_outdoor',
            field=models.BooleanField(default=False, help_text='Mark if the event takes place outdoors to show weather info.', verbose_name='Is outdoor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_text',
            field=models.CharField(blank=True, help_text='Free text location. TODO: replace with Place relation when available.', max_length=255),
        ),
    ]
