# Generated by Django 5.2.8 on 2026-03-10 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació')),
                ('template_slug', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('interval_hours', models.PositiveSmallIntegerField(default=3)),
                ('season_start_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('season_end_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per')),
            ],
            options={
                'verbose_name': 'Automation Job',
                'verbose_name_plural': 'Automation Jobs',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació')),
                ('trigger', models.CharField(choices=[('schedule', 'Schedule'), ('manual', 'Manual'), ('retry', 'Retry')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('window_key', models.CharField(blank=True, max_length=120, null=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automations.automationjob')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per')),
            ],
            options={
                'verbose_name': 'Automation Run',
                'verbose_name_plural': 'Automation Runs',
                'ordering': ('-started_at', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('window_key__isnull', False)), fields=('automation', 'window_key'), name='unique_automation_run_window_per_job')],
            },
        ),
    ]
