# Generated by Django 5.2.8 on 2026-02-04 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0004_add_is_featured_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name of the source (e.g., 'Cabrera de Mar')", max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Unique identifier matching the parser slug', unique=True, verbose_name='Slug')),
                ('base_url', models.URLField(help_text='Base URL of the municipality website', verbose_name='Base URL')),
                ('news_path', models.CharField(default='/actualitat/noticies', help_text='Path to the news listing page', max_length=200, verbose_name='News path')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source should be scraped', verbose_name='Active')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Last scraped')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Parser-specific configuration as JSON', verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scraper Source',
                'verbose_name_plural': 'Scraper Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='Original URL of the news article', verbose_name='Source URL')),
                ('external_id', models.CharField(help_text='Unique identifier from the source (usually slug or path)', max_length=200, verbose_name='External ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('body', models.TextField(blank=True, help_text='Full HTML content', verbose_name='Body')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('featured_image_url', models.URLField(blank=True, verbose_name='Featured image URL')),
                ('gallery_image_urls', models.JSONField(blank=True, default=list, verbose_name='Gallery image URLs')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Status')),
                ('import_error', models.TextField(blank=True, verbose_name='Import error')),
                ('raw_html', models.TextField(blank=True, verbose_name='Raw HTML')),
                ('raw_metadata', models.JSONField(blank=True, default=dict, verbose_name='Raw metadata')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_source', to='news.news', verbose_name='Imported news')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_news', to='scraper.scrapersource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Scraped News',
                'verbose_name_plural': 'Scraped News',
                'ordering': ['-published_at', '-scraped_at'],
                'indexes': [models.Index(fields=['status'], name='scraper_scr_status_469d06_idx'), models.Index(fields=['source', 'status'], name='scraper_scr_source__31c671_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
