# Generated by Django 5.2.8 on 2026-02-05 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)', verbose_name='Progress')),
                ('max_pages', models.IntegerField(help_text='Maximum number of pages to scrape', verbose_name='Max pages')),
                ('pages_scraped', models.IntegerField(default=0, verbose_name='Pages scraped')),
                ('news_found', models.IntegerField(default=0, verbose_name='News found')),
                ('news_created', models.IntegerField(default=0, verbose_name='News created')),
                ('news_updated', models.IntegerField(default=0, verbose_name='News updated')),
                ('news_skipped', models.IntegerField(default=0, verbose_name='News skipped')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to='scraper.scrapersource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Scrape Job',
                'verbose_name_plural': 'Scrape Jobs',
                'ordering': ['-started_at'],
            },
        ),
    ]
