# Generated by Django 5.2.8 on 2026-02-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
