# Generated by Django 4.2.26 on 2025-11-17 16:30

from django.db import migrations, models
import media_files.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/documents/', validators=[media_files.utils.validate_max_file_size, media_files.utils.validate_document_extension])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='uploads/images/', validators=[media_files.utils.validate_max_file_size, media_files.utils.validate_image_extension])),
                ('variant_thumbnail', models.CharField(blank=True, max_length=500)),
                ('variant_medium', models.CharField(blank=True, max_length=500)),
                ('variant_large', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
