# Generated by Django 5.2.8 on 2025-11-17 16:35

import media_files.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(upload_to=media_files.utils.get_document_upload_path, validators=[media_files.utils.validate_max_file_size, media_files.utils.validate_document_extension]),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.ImageField(upload_to=media_files.utils.get_image_upload_path, validators=[media_files.utils.validate_max_file_size, media_files.utils.validate_image_extension]),
        ),
    ]
