# Generated by Django 5.2.8 on 2025-11-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0002_alter_documentfile_file_alter_imagefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='mime_type',
            field=models.CharField(help_text='Tipo MIME del archivo (ej: image/jpeg, application/pdf)', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='original_name',
            field=models.CharField(help_text='Nombre original del archivo al momento de subirlo', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='size_bytes',
            field=models.PositiveBigIntegerField(help_text='Tamaño del archivo en bytes'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='mime_type',
            field=models.CharField(help_text='Tipo MIME del archivo (ej: image/jpeg, application/pdf)', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='original_name',
            field=models.CharField(help_text='Nombre original del archivo al momento de subirlo', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='size_bytes',
            field=models.PositiveBigIntegerField(help_text='Tamaño del archivo en bytes'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='variant_large',
            field=models.CharField(blank=True, help_text='Ruta a variante large (1200px ancho)', max_length=500),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='variant_medium',
            field=models.CharField(blank=True, help_text='Ruta a variante medium (600px ancho)', max_length=500),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='variant_thumbnail',
            field=models.CharField(blank=True, help_text='Ruta a variante thumbnail (150px ancho)', max_length=500),
        ),
    ]
