# Generated by Django 5.2.8 on 2025-11-19 23:46

import django.db.models.deletion
import media_files.utils
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0003_alter_documentfile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDocumentFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Nombre original del archivo al momento de subirlo', max_length=255)),
                ('mime_type', models.CharField(help_text='Tipo MIME del archivo (ej: image/jpeg, application/pdf)', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de creación del registro')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de última actualización')),
                ('file', models.TextField(max_length=100, validators=[media_files.utils.validate_max_file_size, media_files.utils.validate_document_extension])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical document file',
                'verbose_name_plural': 'historical document files',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalImageFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Nombre original del archivo al momento de subirlo', max_length=255)),
                ('mime_type', models.CharField(help_text='Tipo MIME del archivo (ej: image/jpeg, application/pdf)', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de creación del registro')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de última actualización')),
                ('file', models.TextField(max_length=100, validators=[media_files.utils.validate_max_file_size, media_files.utils.validate_image_extension])),
                ('variant_thumbnail', models.CharField(blank=True, help_text='Ruta a variante thumbnail (150px ancho)', max_length=500)),
                ('variant_medium', models.CharField(blank=True, help_text='Ruta a variante medium (600px ancho)', max_length=500)),
                ('variant_large', models.CharField(blank=True, help_text='Ruta a variante large (1200px ancho)', max_length=500)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical image file',
                'verbose_name_plural': 'historical image files',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
