# Generated by Django 5.2.8 on 2025-12-11 23:06

import django.db.models.deletion
import media_files.utils
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0004_historicaldocumentfile_historicalimagefile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Nombre original del archivo al momento de subirlo', max_length=255)),
                ('mime_type', models.CharField(help_text='Tipo MIME del archivo (ej: image/jpeg, application/pdf)', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('file', models.FileField(upload_to=media_files.utils.get_video_upload_path, validators=[media_files.utils.validate_max_file_size, media_files.utils.validate_video_extension])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalVideoFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Nombre original del archivo al momento de subirlo', max_length=255)),
                ('mime_type', models.CharField(help_text='Tipo MIME del archivo (ej: image/jpeg, application/pdf)', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de creación del registro')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de última actualización')),
                ('file', models.TextField(max_length=100, validators=[media_files.utils.validate_max_file_size, media_files.utils.validate_video_extension])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical video file',
                'verbose_name_plural': 'historical video files',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
