labels:
  - name: "type/feature"
    description: "Nueva funcionalidad o mejora visible para usuarios."
    color: "1D76DB"
  - name: "type/bug"
    description: "Corrección de un error que afecta al comportamiento esperado."
    color: "D73A4A"
  - name: "type/chore"
    description: "Tarea de mantenimiento, limpieza o actualización menor."
    color: "FBCA04"
  - name: "type/refactor"
    description: "Refactorización interna sin cambios funcionales."
    color: "C5DEF5"
  - name: "type/docs"
    description: "Trabajo relacionado con documentación."
    color: "5319E7"
  - name: "type/spike"
    description: "Investigación, prototipo o validación rápida de ideas."
    color: "0E8A16"
  - name: "area/frontend"
    description: "Código de interfaz de usuario, componentes y estilos."
    color: "F9D0C4"
  - name: "area/backend"
    description: "APIs, lógica de negocio, integraciones y base de datos."
    color: "FEE39F"
  - name: "area/infra"
    description: "Infraestructura, IaC, CI/CD y despliegues."
    color: "C2E0C6"
  - name: "area/devops"
    description: "Pipelines, observabilidad y tooling operativo."
    color: "C5F1FF"
  - name: "area/docs"
    description: "Documentación funcional o técnica del proyecto."
    color: "E4E669"
  - name: "priority/P0-blocker"
    description: "Bloqueante: requiere atención inmediata."
    color: "B60205"
  - name: "priority/P1-high"
    description: "Alta prioridad: debe atenderse pronto."
    color: "D93F0B"
  - name: "priority/P2-medium"
    description: "Prioridad media: importante pero no urgente."
    color: "FBCA04"
  - name: "priority/P3-low"
    description: "Prioridad baja: se puede planificar más adelante."
    color: "0E8A16"
  - name: "status/ready"
    description: "Listo para que alguien lo tome."
    color: "0E8A16"
  - name: "status/in-progress"
    description: "Trabajo actualmente en curso."
    color: "1D76DB"
  - name: "status/blocked"
    description: "Bloqueado por dependencias externas o problemas pendientes."
    color: "D73A4A"
  - name: "status/needs-review"
    description: "Requiere revisión técnica o funcional."
    color: "5319E7"
  - name: "status/needs-info"
    description: "Falta información o aclaraciones para avanzar."
    color: "FEE39F"
  - name: "status/done"
    description: "Trabajo completado y aprobado."
    color: "7057FF"
  - name: "size/XS"
    description: "Esfuerzo mínimo, menos de media jornada."
    color: "BFE5BF"
  - name: "size/S"
    description: "Esfuerzo pequeño, hasta una jornada."
    color: "99D1B9"
  - name: "size/M"
    description: "Esfuerzo medio, entre una y dos jornadas."
    color: "6FBA82"
  - name: "size/L"
    description: "Esfuerzo grande, varios días de trabajo."
    color: "3E8E41"
  - name: "size/XL"
    description: "Esfuerzo muy grande, requiere planificación dedicada."
    color: "196127"
