import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Edit, Trash2 } from "lucide-react";
import { getCategoryIcon } from "../constants/icons";
export function CategoriesTable({ categories, onEdit, onDelete }) {
    const parentMap = new Map(categories.map((c) => [c.id, c]));
    return (_jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "min-w-full divide-y divide-border text-sm", children: [_jsx("thead", { className: "bg-muted/50", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-2 text-left font-semibold text-foreground", children: "Slug" }), _jsx("th", { className: "px-4 py-2 text-left font-semibold text-foreground", children: "Icono" }), _jsx("th", { className: "px-4 py-2 text-left font-semibold text-foreground", children: "Nombre" }), _jsx("th", { className: "px-4 py-2 text-left font-semibold text-foreground", children: "Padre" }), _jsx("th", { className: "px-4 py-2 text-left font-semibold text-foreground", children: "Taxonom\u00EDa" }), _jsx("th", { className: "px-4 py-2 text-right font-semibold text-foreground", children: "Acciones" })] }) }), _jsxs("tbody", { className: "divide-y divide-border", children: [categories.map((cat) => {
                            const IconComponent = getCategoryIcon(cat.icon);
                            const parent = cat.parent ? parentMap.get(cat.parent) : null;
                            return (_jsxs("tr", { className: "hover:bg-muted/40", children: [_jsx("td", { className: "px-4 py-2 font-medium text-foreground", children: cat.slug }), _jsx("td", { className: "px-4 py-2", children: IconComponent ? (_jsx("div", { className: "flex h-9 w-9 items-center justify-center rounded-md border border-border/60 bg-muted/30", children: _jsx(IconComponent, { className: "h-4 w-4" }) })) : (_jsx("span", { className: "text-muted-foreground", children: "-" })) }), _jsxs("td", { className: "px-4 py-2", children: [_jsx("div", { className: "font-medium", children: cat.nombre }), cat.descripcion && (_jsx("div", { className: "text-xs text-muted-foreground line-clamp-2", children: cat.descripcion }))] }), _jsx("td", { className: "px-4 py-2", children: parent ? (_jsxs("div", { className: "text-sm text-foreground", children: [parent.nombre, " ", _jsxs("span", { className: "text-muted-foreground", children: ["(", parent.slug, ")"] })] })) : (_jsx("span", { className: "text-muted-foreground", children: "-" })) }), _jsx("td", { className: "px-4 py-2", children: cat.taxonomy ? _jsx(Badge, { variant: "secondary", children: cat.taxonomy }) : _jsx("span", { children: "-" }) }), _jsx("td", { className: "px-4 py-2 text-right", children: _jsxs("div", { className: "flex justify-end gap-1", children: [_jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 text-muted-foreground hover:text-foreground hover:bg-muted", onClick: () => onEdit(cat), "aria-label": `Editar ${cat.nombre}`, children: _jsx(Edit, { className: "h-4 w-4" }) }), _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 text-muted-foreground hover:text-destructive hover:bg-destructive/10", onClick: () => onDelete(cat.id), "aria-label": `Eliminar ${cat.nombre}`, children: _jsx(Trash2, { className: "h-4 w-4" }) })] }) })] }, cat.id));
                        }), categories.length === 0 && (_jsx("tr", { children: _jsx("td", { colSpan: 6, className: "px-4 py-6 text-center text-muted-foreground", children: "No hay categor\u00EDas." }) }))] })] }) }));
}
