"""Signals for Route lifecycle cleanup."""

from __future__ import annotations

from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver

from media_files.models import DocumentFile

from .models import Route


def _is_autogenerated_route_gpx(route_slug: str, document: DocumentFile | None) -> bool:
    """Return True when the document matches the naming convention of generated GPX."""
    if not document:
        return False

    expected_name = f"{route_slug}.gpx"
    original_name = (document.original_name or "").strip()
    return original_name == expected_name


def _document_is_shared_elsewhere(
    document: DocumentFile,
    *,
    ignore_routes_gpx_route_id: int | None = None,
    ignore_attached_route_id: int | None = None,
) -> bool:
    """
    Avoid deleting GPX documents that are reused outside route.gpx_file.

    Auto-generated files are expected to be route-private; this guard protects
    manually reused assets.
    """
    attached_to_routes = getattr(document, "attached_to_routes", None)
    if attached_to_routes is not None:
        attached_qs = attached_to_routes.all()
        if ignore_attached_route_id is not None:
            attached_qs = attached_qs.exclude(pk=ignore_attached_route_id)
        if attached_qs.exists():
            return True

    routes_gpx = getattr(document, "routes_gpx", None)
    if routes_gpx is not None:
        gpx_qs = routes_gpx.all()
        if ignore_routes_gpx_route_id is not None:
            gpx_qs = gpx_qs.exclude(pk=ignore_routes_gpx_route_id)
        if gpx_qs.exists():
            return True

    relation_names = (
        "attached_to_events",
        "attached_to_news",
        "attached_to_places",
        "programs_festes",
    )
    for relation_name in relation_names:
        relation_manager = getattr(document, relation_name, None)
        if relation_manager is not None and relation_manager.all().exists():
            return True
    return False


@receiver(pre_save, sender=Route)
def cleanup_replaced_generated_gpx(sender, instance: Route, **kwargs) -> None:
    """Delete old generated GPX when a route swaps to another gpx_file."""
    if not instance.pk:
        return

    try:
        previous = sender.objects.select_related("gpx_file").get(pk=instance.pk)
    except sender.DoesNotExist:
        return

    old_gpx = previous.gpx_file
    gpx_has_changed = previous.gpx_file_id != instance.gpx_file_id
    if not gpx_has_changed or not _is_autogenerated_route_gpx(previous.slug, old_gpx):
        return

    if old_gpx and not _document_is_shared_elsewhere(
        old_gpx, ignore_routes_gpx_route_id=previous.pk
    ):
        old_gpx.delete()


@receiver(pre_delete, sender=Route)
def cleanup_generated_gpx_on_route_delete(sender, instance: Route, **kwargs) -> None:
    """Delete generated GPX when deleting a route if the asset is not shared."""
    current = sender.objects.select_related("gpx_file").filter(pk=instance.pk).first()
    if not current:
        return

    gpx = current.gpx_file
    if not _is_autogenerated_route_gpx(current.slug, gpx):
        return

    if gpx and not _document_is_shared_elsewhere(
        gpx,
        ignore_routes_gpx_route_id=instance.pk,
        ignore_attached_route_id=instance.pk,
    ):
        gpx.delete()
