# Generated by Django 5.2.8 on 2025-12-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_pages', '0001_initial'),
        ('media_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom del site')),
                ('tagline', models.CharField(blank=True, default='', max_length=255, verbose_name='Claim/Tagline')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Telèfon')),
                ('support_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de suport')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de contacte')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Adreça')),
                ('schedule', models.CharField(blank=True, default='', max_length=255, verbose_name='Horari')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='Twitter/X')),
                ('youtube_url', models.URLField(blank=True, default='', verbose_name='YouTube')),
                ('maps_base_url', models.URLField(blank=True, default='', verbose_name='Maps base URL')),
                ('analytics_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Analytics ID')),
                ('captcha_site_key', models.CharField(blank=True, default='', max_length=200, verbose_name='Captcha site key')),
                ('show_language_switcher', models.BooleanField(default=True, verbose_name="Mostrar selector d'idioma (BETA)")),
                ('show_social_footer', models.BooleanField(default=True, verbose_name='Mostrar xarxes al footer (BETA)')),
                ('default_metatitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Metatítol per defecte')),
                ('default_metadescription', models.TextField(blank=True, default='', verbose_name='Metadescripció per defecte')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logo', to='media_files.imagefile', verbose_name='Logo')),
                ('logo_dark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logo_dark', to='media_files.imagefile', verbose_name='Logo (dark)')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_favicon', to='media_files.imagefile', verbose_name='Favicon')),
                ('default_og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_default_og', to='media_files.imagefile', verbose_name='Imatge OG per defecte')),
                ('privacy_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_settings', to='static_pages.staticpage', verbose_name='Pàgina de privacitat')),
                ('cookies_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookies_settings', to='static_pages.staticpage', verbose_name='Pàgina de cookies')),
                ('legal_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_settings', to='static_pages.staticpage', verbose_name='Avís legal')),
                ('inclusion_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inclusion_settings', to='static_pages.staticpage', verbose_name='Diversitat i inclusió')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
