# Generated by Django 5.2.8 on 2025-12-11 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0005_videofile_historicalvideofile'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_background_video', to='media_files.videofile', verbose_name='Vídeo de fons'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_description_internal',
            field=models.TextField(blank=True, default='', verbose_name='Descripció interna del vídeo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Títol del vídeo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, default='', verbose_name='Vídeo YouTube'),
        ),
    ]
