# Generated by Django 5.2.8 on 2025-12-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_background_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='video_enabled',
            field=models.BooleanField(default=True, help_text='Activa o desactiva el vÇðdeo de fons de la home.', verbose_name='Activar vÇðdeo del hero'),
        ),
    ]
