# Generated by Django 5.2.8 on 2025-12-12 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_category_parent"),
        ("site_settings", "0003_sitesettings_video_enabled"),
        ("static_pages", "0002_alter_staticpage_fecha_creacion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "location",
                    models.CharField(
                        choices=[("header", "Header"), ("footer", "Footer")],
                        default="header",
                        max_length=20,
                        verbose_name="Ubicación",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("category", "Categoría"),
                            ("static_page", "Página estática"),
                            ("custom", "Link personalizado"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("url", models.URLField(blank=True, default="", verbose_name="URL personalizada")),
                ("label", models.CharField(blank=True, default="", max_length=200, verbose_name="Etiqueta")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="core.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="site_settings.menuitem",
                        verbose_name="Padre",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="site_settings.sitesettings",
                        verbose_name="Configuración del site",
                    ),
                ),
                (
                    "static_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="static_pages.staticpage",
                        verbose_name="Página estática",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "ordering": ("location", "parent_id", "order", "id"),
            },
        ),
    ]

