# Generated by Django 5.2.8 on 2026-01-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud del centre del poble', max_digits=9, max_length=50, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud del centre del poble', max_digits=9, max_length=50, null=True, verbose_name='Longitud'),
        ),
    ]
