# Generated by Django 5.2.8 on 2026-01-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sitesettings_latitude_sitesettings_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='alert_enabled',
            field=models.BooleanField(default=False, help_text="Mostra una barra d'avís a tota la web para comunicats urgents.", verbose_name='Activar avís global'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_link',
            field=models.URLField(blank=True, default='', help_text="URL opcional para 'Saber més'.", verbose_name="Enllaç de l'avís"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_message',
            field=models.TextField(blank=True, default='', help_text="Text que es mostrarà a la barra d'avís.", verbose_name="Missatge de l'avís"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_type',
            field=models.CharField(choices=[('info', 'Informació (Blau)'), ('success', 'Èxit (Verd)'), ('warning', 'Advertència (Taronja)'), ('danger', 'Urgent/Perill (Vermell)')], default='info', max_length=20, verbose_name="Tipus d'avís"),
        ),
    ]
