# Generated by Django 5.2.8 on 2026-01-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_sitesettings_alert_enabled_sitesettings_alert_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='alert_end_at',
            field=models.DateTimeField(blank=True, help_text="L'avís s'ocultarà automàticament després d'aquesta data (opcional).", null=True, verbose_name="Data de fi de l'avís"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_start_at',
            field=models.DateTimeField(blank=True, help_text="L'avís no es mostrarà abans d'aquesta data (opcional).", null=True, verbose_name="Data d'inici de l'avís"),
        ),
    ]
