# Generated by Django 5.2.8 on 2026-02-19 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_sitesettings_alert_end_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_weather_api_key',
            field=models.CharField(blank=True, default='', help_text='API Key per a la integració amb Google Cloud Weather API.', max_length=200, verbose_name='Google Weather API Key'),
        ),
        migrations.CreateModel(
            name='MunicipalityWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació')),
                ('forecast_data', models.JSONField(help_text='Detailed JSON forecast for the next 7 days.', verbose_name='Forecast Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per')),
            ],
            options={
                'verbose_name': 'Municipality Weather',
                'verbose_name_plural': 'Municipality Weather',
                'ordering': ('-updated_at',),
            },
        ),
    ]
