# Generated by Django 5.2.8 on 2026-03-08 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_routes_festes_taxonomy'),
        ('media_files', '0005_videofile_historicalvideofile'),
        ('site_settings', '0008_sitesettings_google_weather_api_key_and_more'),
        ('static_pages', '0002_alter_staticpage_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, default='', max_length=120, verbose_name='Eyebrow')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('show_social_links', models.BooleanField(default=True, verbose_name='Mostrar enlaces sociales')),
                ('show_contact_block', models.BooleanField(default=True, verbose_name='Mostrar bloque de contacto')),
                ('show_badges_block', models.BooleanField(default=True, verbose_name='Mostrar bloque de sellos')),
                ('copyright_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Texto de copyright')),
                ('site_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer_settings', to='site_settings.sitesettings', verbose_name='Configuración del site')),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('explore', 'Explorar'), ('institutional', 'Institucional')], default='explore', max_length=30, verbose_name='Sección')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('type', models.CharField(choices=[('category', 'Categoría'), ('static_page', 'Página estática'), ('custom', 'Link personalizado')], max_length=20, verbose_name='Tipo')),
                ('label', models.CharField(blank=True, default='', max_length=200, verbose_name='Etiqueta')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL personalizada')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_links', to='core.category', verbose_name='Categoría')),
                ('static_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_links', to='static_pages.staticpage', verbose_name='Página estática')),
                ('footer_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='site_settings.footersettings', verbose_name='Configuración del footer')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ('section', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FooterBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Texto alternativo')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='Enlace')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_badges', to='media_files.imagefile', verbose_name='Imagen')),
                ('footer_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='site_settings.footersettings', verbose_name='Configuración del footer')),
            ],
            options={
                'verbose_name': 'Footer Badge',
                'verbose_name_plural': 'Footer Badges',
                'ordering': ('order', 'id'),
            },
        ),
    ]
