# Generated by Django 5.2.8 on 2026-05-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_footer_singleton_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendent'), ('running', 'En progrés'), ('success', 'Completat'), ('failed', 'Fallit')], default='pending', max_length=20, verbose_name='Estat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat el')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciat el')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalitzat el')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="Missatge d'error")),
                ('theme_config', models.JSONField(default=dict, verbose_name='Configuració de tema')),
            ],
            options={
                'verbose_name': 'Build Job',
                'verbose_name_plural': 'Build Jobs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuració visual activa en format JSON.', verbose_name='Configuració de tema (esborrany)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_config_published',
            field=models.JSONField(blank=True, default=dict, help_text='Configuració visual publicada en format JSON.', verbose_name='Configuració de tema (publicat)'),
        ),
    ]
