# Generated by Django 5.2.8 on 2026-06-02 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_initial'),
        ('site_settings', '0010_buildjob_sitesettings_theme_config_and_more'),
        ('static_pages', '0002_alter_staticpage_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerbadge',
            name='footer_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='site_settings.footersettings', verbose_name='Configuración del footer'),
        ),
        migrations.AlterField(
            model_name='footerbadge',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_links', to='core.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='footer_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='site_settings.footersettings', verbose_name='Configuración del footer'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='section',
            field=models.CharField(choices=[('explore', 'Explorar'), ('institutional', 'Institucional')], default='explore', max_length=30, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='static_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_links', to='static_pages.staticpage', verbose_name='Página estática'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='site_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer_settings', to='site_settings.sitesettings', verbose_name='Configuración del site'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Título'),
        ),
    ]
