import { StaticPage } from "@/features/static-pages/types";
export type LinkedImage = {
  id: number;
  original_name: string;
  file: string;
  mime_type?: string;
  variant_thumbnail?: string;
  thumbnail_url?: string;
};
export type SiteSettings = {
  id?: number;
  site_name: string;
  tagline: string;
  logo?: LinkedImage | null;
  logo_id?: number | null;
  logo_dark?: LinkedImage | null;
  logo_dark_id?: number | null;
  favicon?: LinkedImage | null;
  favicon_id?: number | null;
  phone: string;
  support_email: string;
  contact_email: string;
  address: string;
  schedule: string;
  facebook_url: string;
  instagram_url: string;
  twitter_url: string;
  youtube_url: string;
  video_enabled: boolean;
  video_title: string;
  video_description_internal: string;
  background_video?: LinkedVideo | null;
  background_video_id?: number | null;
  maps_base_url: string;
  analytics_id: string;
  captcha_site_key: string;
  show_language_switcher: boolean;
  show_social_footer: boolean;
  privacy_page?: StaticPage | null;
  privacy_page_id?: number | null;
  cookies_page?: StaticPage | null;
  cookies_page_id?: number | null;
  legal_page?: StaticPage | null;
  legal_page_id?: number | null;
  inclusion_page?: StaticPage | null;
  inclusion_page_id?: number | null;
  default_metatitle: string;
  default_metadescription: string;
  default_og_image?: LinkedImage | null;
  default_og_image_id?: number | null;
};
export type LinkedVideo = {
  id: number;
  original_name: string;
  file: string;
  mime_type?: string;
};
export type SiteSettingsPayload = Partial<SiteSettings>;
export type SiteSettingsUploadPayload = SiteSettingsPayload & {
  logo_file?: File | null;
  logo_dark_file?: File | null;
  favicon_file?: File | null;
};
