# Generated by Django 5.2.8 on 2026-01-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel'), ('apartment', 'Apartment'), ('campsite', 'Campsite'), ('rural', 'Rural House'), ('other', 'Other')], default='hotel', max_length=50, verbose_name='Accommodation Type')),
                ('stars', models.PositiveSmallIntegerField(blank=True, help_text='Star rating (1-5)', null=True, verbose_name='Stars')),
                ('amenities', models.JSONField(blank=True, default=dict, help_text='JSON object with boolean flags: wifi, pool, parking, ac, etc.', verbose_name='Amenities')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Check-in Time')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Check-out Time')),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('cuisine_type', models.CharField(choices=[('mediterranean', 'Mediterranean'), ('italian', 'Italian'), ('asian', 'Asian'), ('fast_food', 'Fast Food'), ('traditional', 'Traditional'), ('tapas', 'Tapas'), ('vegan', 'Vegan/Vegetarian'), ('other', 'Other')], default='other', max_length=50, verbose_name='Cuisine Type')),
                ('amenities', models.JSONField(blank=True, default=dict, help_text='JSON object with boolean flags: wifi, terrace, pet_friendly, etc.', verbose_name='Amenities')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Total seating capacity', null=True, verbose_name='Capacity')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
            bases=('places.place',),
        ),
    ]
