# Generated by Django 5.2.8 on 2026-03-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0005_videofile_historicalvideofile'),
        ('places', '0002_accommodation_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('beach_type', models.CharField(choices=[('urban', 'Urban'), ('cove', 'Cove'), ('natural', 'Natural')], default='urban', max_length=20, verbose_name='Beach Type')),
                ('environment_summary', models.CharField(blank=True, max_length=255, verbose_name='Environment Summary')),
                ('recommended_for', models.JSONField(blank=True, default=list, help_text='JSON array of audience tags such as families or sunset.', verbose_name='Recommended For')),
                ('length_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Length (m)')),
                ('access_notes', models.TextField(blank=True, verbose_name='Access Notes')),
                ('parking_info', models.TextField(blank=True, verbose_name='Parking Information')),
                ('public_transport_info', models.TextField(blank=True, verbose_name='Public Transport Information')),
                ('services', models.JSONField(blank=True, default=dict, help_text='JSON object of service booleans.', verbose_name='Services')),
                ('accessibility_features', models.JSONField(blank=True, default=dict, help_text='JSON object of accessibility feature booleans.', verbose_name='Accessibility Features')),
                ('gallery', models.ManyToManyField(blank=True, related_name='in_beach_galleries', to='media_files.imagefile', verbose_name='Gallery')),
            ],
            options={
                'verbose_name': 'Beach',
                'verbose_name_plural': 'Beaches',
            },
            bases=('places.place',),
        ),
    ]
