# Generated by Django 5.2.8 on 2026-02-03 22:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_add_routes_festes_taxonomy'),
        ('media_files', '0005_videofile_historicalvideofile'),
        ('places', '0002_accommodation_restaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol')),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció')),
                ('slug', models.SlugField(help_text='Identificador únic per a URLs', max_length=150, unique=True, verbose_name='Slug')),
                ('route_type', models.CharField(choices=[('walking', 'A peu'), ('cycling', 'Bicicleta'), ('guided', 'Guiada'), ('mixed', 'Mixta')], default='walking', max_length=20, verbose_name='Tipus de ruta')),
                ('difficulty', models.CharField(choices=[('easy', 'Fàcil'), ('moderate', 'Moderada'), ('difficult', 'Difícil'), ('expert', 'Expert')], default='moderate', max_length=20, verbose_name='Dificultat')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distància (km)')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duració (minuts)')),
                ('elevation_gain', models.PositiveIntegerField(blank=True, null=True, verbose_name='Desnivell positiu (m)')),
                ('elevation_loss', models.PositiveIntegerField(blank=True, null=True, verbose_name='Desnivell negatiu (m)')),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud inici')),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud inici')),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud fi')),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud fi')),
                ('is_circular', models.BooleanField(default=False, verbose_name='Ruta circular')),
                ('track_geojson', models.JSONField(blank=True, help_text='LineString o MultiLineString en format GeoJSON', null=True, verbose_name='Track GeoJSON')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicada')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('attachments', models.ManyToManyField(blank=True, related_name='attached_to_routes', to='media_files.documentfile', verbose_name='Documents adjunts')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core.category', verbose_name='Categoria')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per')),
                ('featured_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_routes', to='media_files.imagefile', verbose_name='Imatge destacada')),
                ('gallery', models.ManyToManyField(blank=True, related_name='in_route_galleries', to='media_files.imagefile', verbose_name="Galeria d'imatges")),
                ('gpx_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_gpx', to='media_files.documentfile', verbose_name='Arxiu GPX/KML')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per')),
                ('tags', models.ManyToManyField(blank=True, related_name='routes', to='core.tag')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutes',
                'ordering': ('-fecha_creacion',),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RouteCategorySingleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Categoria de rutes')),
            ],
            options={
                'verbose_name': 'Route Category Singleton',
                'verbose_name_plural': 'Route Category Singleton',
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('instructions', models.TextField(blank=True, verbose_name='Instruccions')),
                ('distance_from_previous_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Distància des de l'anterior (km)")),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoint_routes', to='places.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_waypoints', to='routes.route')),
            ],
            options={
                'verbose_name': 'Waypoint',
                'verbose_name_plural': 'Waypoints',
                'ordering': ('order',),
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.AddField(
            model_name='route',
            name='waypoints',
            field=models.ManyToManyField(related_name='on_routes', through='routes.RouteWaypoint', to='places.place', verbose_name="Punts d'interès"),
        ),
        migrations.CreateModel(
            name='RouteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Títol')),
                ('summary', models.TextField(blank=True, verbose_name='Resum')),
                ('description', models.TextField(blank=True, verbose_name='Descripció')),
                ('instructions', models.TextField(blank=True, verbose_name='Instruccions')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='routes.route')),
            ],
            options={
                'verbose_name': 'Ruta Translation',
                'db_table': 'routes_route_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
