# Generated by Django 5.2.8 on 2026-03-01 17:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0005_videofile_historicalvideofile'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('title', models.CharField(max_length=200, verbose_name='Títol')),
                ('description', models.TextField(blank=True, verbose_name='Descripció')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actiu')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_checkpoints', to='media_files.imagefile', verbose_name='Imatge')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_checkpoints', to='routes.route')),
            ],
            options={
                'verbose_name': 'Checkpoint de ruta',
                'verbose_name_plural': 'Checkpoints de rutes',
                'ordering': ('order',),
                'unique_together': {('route', 'order')},
            },
        ),
    ]
