# Generated by Django 5.2.8 on 2026-03-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_routecheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='android_app_url',
            field=models.URLField(blank=True, help_text='URL a Google Play Store (ex. Natura Local)', max_length=500, null=True, verbose_name='Enllaç Android App'),
        ),
        migrations.AddField(
            model_name='route',
            name='ios_app_url',
            field=models.URLField(blank=True, help_text="URL a l'App Store d'Apple (ex. Natura Local)", max_length=500, null=True, verbose_name='Enllaç iOS App'),
        ),
    ]
