# Generated by Django 5.2.8 on 2026-02-03 22:07

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_add_routes_festes_taxonomy'),
        ('events', '0009_make_dates_optional'),
        ('media_files', '0005_videofile_historicalvideofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Festa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol')),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció')),
                ('slug', models.SlugField(help_text='Identificador únic per a URLs', max_length=150, unique=True, verbose_name='Slug')),
                ('start_date', models.DateField(verbose_name='Data inici')),
                ('end_date', models.DateField(verbose_name='Data fi')),
                ('year', models.PositiveIntegerField(verbose_name='Any')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicada')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('is_current', models.BooleanField(default=False, help_text='Marca la festa que es mostra per defecte', verbose_name='És la festa actual')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='festes', to='core.category', verbose_name='Categoria')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per')),
                ('events', models.ManyToManyField(blank=True, related_name='part_of_festa', to='events.event', verbose_name='Esdeveniments')),
                ('featured_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_festes', to='media_files.imagefile', verbose_name='Cartell / Imatge destacada')),
                ('gallery', models.ManyToManyField(blank=True, related_name='in_festa_galleries', to='media_files.imagefile', verbose_name="Galeria d'imatges")),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posters_festes', to='media_files.imagefile', verbose_name='Cartell oficial')),
                ('program_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_festes', to='media_files.documentfile', verbose_name='Programa PDF')),
                ('tags', models.ManyToManyField(blank=True, related_name='festes', to='core.tag')),
            ],
            options={
                'verbose_name': 'Festa',
                'verbose_name_plural': 'Festes',
                'ordering': ('-year', '-start_date'),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FestaCategorySingleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Categoria de festes')),
            ],
            options={
                'verbose_name': 'Festa Category Singleton',
                'verbose_name_plural': 'Festa Category Singleton',
            },
        ),
        migrations.CreateModel(
            name='FestaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Títol')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítol')),
                ('summary', models.TextField(blank=True, verbose_name='Resum')),
                ('description', models.TextField(blank=True, verbose_name='Descripció')),
                ('program_text', models.TextField(blank=True, verbose_name='Programa (text)')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='festes.festa')),
            ],
            options={
                'verbose_name': 'Festa Translation',
                'db_table': 'festes_festa_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('website', models.URLField(blank=True, verbose_name='Web')),
                ('tier', models.CharField(choices=[('platinum', 'Platí'), ('gold', 'Or'), ('silver', 'Plata'), ('bronze', 'Bronze'), ('collaborator', 'Col·laborador')], default='collaborator', max_length=20, verbose_name='Nivell')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='festes.festa', verbose_name='Festa')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_logos', to='media_files.imagefile', verbose_name='Logotip')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadors',
                'ordering': ('tier', 'order'),
            },
        ),
        migrations.AddConstraint(
            model_name='festa',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_current_festa'),
        ),
        migrations.AlterUniqueTogether(
            name='festatranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
