# Generated by Django 5.2.8 on 2026-02-24 11:38

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Adreça')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Codi Postal')),
                ('city', models.CharField(max_length=200, verbose_name='Ciutat')),
                ('latitude', models.FloatField(blank=True, help_text='Latitud en graus decimals (-90 a 90)', null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(blank=True, help_text='Longitud en graus decimals (-180 a 180)', null=True, verbose_name='Longitud')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicada')),
                ('is_accessible', models.BooleanField(default=False, help_text='Indicar si la ubicació és accessible per a mobilitat reduïda', verbose_name='Accessible')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Data creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Data modificació')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ('slug',),
                'indexes': [models.Index(fields=['slug'], name='festes_venu_slug_02f34c_idx')],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VenueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Descripció')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='festes.venue')),
            ],
            options={
                'verbose_name': 'Venue Translation',
                'db_table': 'festes_venue_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
