# Generated by Django 5.2.8 on 2026-02-24 12:09

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festes', '0002_venue_venuetranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada')], default='draft', max_length=20, verbose_name='Estat')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data inici')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data fi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Data creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Data modificació')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='festes.festa', verbose_name='Festa')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programes',
                'ordering': ('festa', 'order'),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Inici')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Fi')),
                ('is_free', models.BooleanField(default=True, verbose_name='Gratis')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Preu indicatiu de l'activitat. Null quan és gratuïta.", max_digits=10, null=True, verbose_name='Preu')),
                ('price_text', models.CharField(blank=True, default='', max_length=120, verbose_name='Text del preu')),
                ('ticket_url', models.URLField(blank=True, null=True, verbose_name='URL tickets')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada')], default='draft', max_length=20, verbose_name='Estat')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Data creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Data modificació')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='festes.venue', verbose_name='Venue')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='festes.program', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ('start_at', 'id'),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProgramTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Títol')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítol')),
                ('description', models.TextField(blank=True, verbose_name='Descripció')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='festes.program')),
            ],
            options={
                'verbose_name': 'Programa Translation',
                'db_table': 'festes_program_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Títol')),
                ('summary', models.CharField(blank=True, max_length=280, verbose_name='Resum')),
                ('description', models.TextField(blank=True, verbose_name='Descripció')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='festes.activity')),
            ],
            options={
                'verbose_name': 'Activity Translation',
                'db_table': 'festes_activity_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['festa', 'order'], name='festes_prog_festa_i_c59e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['slug'], name='festes_prog_slug_60418e_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['program', 'start_at'], name='festes_acti_program_b44208_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category'], name='festes_acti_categor_523cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status', 'start_at'], name='festes_acti_status_32bf22_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['slug'], name='festes_acti_slug_1876ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programtranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
