# Generated by Django 5.2.8 on 2026-02-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festes', '0003_program_activity_programtranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(max_length=160, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(max_length=160, unique=True, verbose_name='Slug'),
        ),
    ]
