# Generated by Django 5.2.8 on 2026-02-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festes', '0004_alter_program_slug_alter_venue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(max_length=160, unique=True, verbose_name='Slug'),
        ),
    ]
