# Generated by Django 5.2.8 on 2026-02-24 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_is_outdoor_alter_event_location_text'),
        ('festes', '0005_alter_activity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='festes_activities', to='events.event', verbose_name='Esdeveniment vinculat'),
        ),
    ]
