# Generated by Django 5.2.8 on 2026-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festes', '0006_activity_event'),
        ('media_files', '0005_videofile_historicalvideofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='festa',
            name='program_images',
            field=models.ManyToManyField(blank=True, help_text='Imatges de les pàgines del programa per mostrar-les com a carrusel.', related_name='program_brochures_festes', to='media_files.imagefile', verbose_name='Imatges del Programa (Folleto)'),
        ),
    ]
