# Generated by Django 5.2.8 on 2026-02-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festes', '0007_festa_program_images'),
        ('media_files', '0005_videofile_historicalvideofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festa',
            name='poster',
        ),
        migrations.AddField(
            model_name='festa',
            name='posters',
            field=models.ManyToManyField(blank=True, help_text='Un o més cartells de la festa.', related_name='posters_festes', to='media_files.imagefile', verbose_name='Cartells oficials'),
        ),
    ]
