# Generated by Django 5.2.8 on 2026-02-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festes', '0008_remove_festa_poster_festa_posters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festa',
            name='program_images',
        ),
    ]
