# Generated by Django 5.2.8 on 2026-02-25 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_is_outdoor_alter_event_location_text'),
        ('festes', '0009_remove_festa_program_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festes.festa')),
            ],
            options={
                'verbose_name': 'Event de Festa',
                'verbose_name_plural': 'Events de Festa',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='festa',
            name='events',
        ),
        migrations.AddField(
            model_name='festa',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='part_of_festa', through='festes.FestaEvent', to='events.event', verbose_name='Esdeveniments'),
        ),
        migrations.AddConstraint(
            model_name='festaevent',
            constraint=models.UniqueConstraint(fields=('festa', 'event'), name='unique_festa_event_link'),
        ),
    ]
