# Generated by Django 5.2.8 on 2026-02-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("festes", "0010_festaevent_alter_festa_events_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivityTranslation",
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
    ]
