# Generated by Django 5.2.8 on 2026-02-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festes', '0011_remove_activity_model'),
        ('media_files', '0005_videofile_historicalvideofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festa',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Marca la festa que es mostra per defecte', verbose_name='És la festa actual'),
        ),
        migrations.AlterField(
            model_name='festa',
            name='posters',
            field=models.ManyToManyField(blank=True, help_text='Un o més cartells de la festa.', related_name='posters_festes', to='media_files.imagefile', verbose_name='Cartells oficials'),
        ),
        migrations.AlterField(
            model_name='festatranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='festatranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtítol'),
        ),
        migrations.AlterField(
            model_name='festatranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='program',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data creació'),
        ),
        migrations.AlterField(
            model_name='program',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modificació'),
        ),
        migrations.AlterField(
            model_name='programtranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='programtranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtítol'),
        ),
        migrations.AlterField(
            model_name='programtranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='tier',
            field=models.CharField(choices=[('platinum', 'Platí'), ('gold', 'Or'), ('silver', 'Plata'), ('bronze', 'Bronze'), ('collaborator', 'Col·laborador')], default='collaborator', max_length=20, verbose_name='Nivell'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adreça'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data creació'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modificació'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='is_accessible',
            field=models.BooleanField(default=False, help_text='Indicar si la ubicació és accessible per a mobilitat reduïda', verbose_name='Accessible'),
        ),
        migrations.AlterField(
            model_name='venuetranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripció'),
        ),
    ]
