import os
from pathlib import Path

import pytest
from django.core.exceptions import ValidationError
from django.core.files import File

from core.models import Category
from places.models import Place, PlaceCategorySingleton
from media_files.models import DocumentFile, ImageFile

pytestmark = pytest.mark.django_db


@pytest.fixture
def media_root(settings, tmp_path):
    settings.MEDIA_ROOT = tmp_path
    return tmp_path


@pytest.fixture
def sample_files_path() -> Path:
    return Path(__file__).resolve().parent / "files"


@pytest.fixture
def places_category() -> Category:
    """Create the default places category."""
    category = Category.objects.create(nombre="Places", slug="places")
    category.set_current_language("ca")
    category.nombre = "Llocs"
    category.save()
    category.set_current_language("es")
    category.nombre = "Lugares"
    category.save()
    return category


@pytest.fixture
def places_singleton(places_category) -> PlaceCategorySingleton:
    """Create the places category singleton."""
    singleton = PlaceCategorySingleton.objects.create(category=places_category)
    return singleton


@pytest.fixture
def sample_document(sample_files_path) -> DocumentFile:
    pdf_path = sample_files_path / "sample.pdf"
    with pdf_path.open("rb") as source:
        return DocumentFile.objects.create(
            file=File(source, name=pdf_path.name),
            original_name=pdf_path.name,
            mime_type="application/pdf",
            size_bytes=os.path.getsize(pdf_path),
        )


@pytest.fixture
def sample_image(sample_files_path) -> ImageFile:
    image_path = sample_files_path / "sample.png"
    with image_path.open("rb") as source:
        return ImageFile.objects.create(
            file=File(source, name=image_path.name),
            original_name=image_path.name,
            mime_type="image/png",
            size_bytes=os.path.getsize(image_path),
        )


def test_create_place_basic(media_root, places_singleton):
    place = Place.objects.create(
        title="Central Park",
        description="Large park",
        latitude=10.0,
        longitude=20.0,
    )

    assert place.pk is not None
    assert place.slug.startswith("central-park")
    assert place.safe_translation_getter("title", any_language=True) == "Central Park"
    assert place.created_at is not None
    assert place.updated_at is not None
    assert place.category == places_singleton.category


def test_lat_lon_validation_range(media_root, places_singleton):
    with pytest.raises(ValidationError):
        Place.objects.create(title="Invalid", latitude=100.0, longitude=0.0)
    with pytest.raises(ValidationError):
        Place.objects.create(title="Invalid", latitude=0.0, longitude=-200.0)


def test_lat_lon_both_required(media_root, places_singleton):
    with pytest.raises(ValidationError):
        Place.objects.create(title="Only lat", latitude=10.0)


def test_slug_autogenerated_and_unique(media_root, places_singleton):
    place_one = Place.objects.create(title="My Place")
    place_two = Place.objects.create(title="My Place")

    assert place_one.slug == "my-place"
    assert place_two.slug == "my-place-2"


def test_template_key(media_root, places_singleton):
    category = Category.objects.create(slug="restaurant", nombre="Restaurant", taxonomy="template")
    place = Place.objects.create(title="Bistro", category=category)

    assert place.template_key == "restaurant"


def test_place_can_attach_media(media_root, places_singleton, sample_document, sample_image):
    place = Place.objects.create(title="Media Place", featured_media=sample_image)
    place.attachments.add(sample_document)

    assert place.featured_media == sample_image
    assert place.attachments.count() == 1


def test_place_category_singleton(places_category):
    """Test that PlaceCategorySingleton works correctly."""
    singleton = PlaceCategorySingleton.objects.create(category=places_category)

    assert singleton.category == places_category
    assert PlaceCategorySingleton.get_default_category() == places_category

    same_singleton = PlaceCategorySingleton.get_solo()
    assert same_singleton.pk == singleton.pk


def test_place_auto_assigns_category(places_singleton):
    place = Place.objects.create(title="Auto Category Test")

    assert place.category == places_singleton.category
