# Generated by Django 5.2.8 on 2026-05-31 21:39

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_initial'),
        ('media_files', '0005_videofile_historicalvideofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol')),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció')),
                ('slug', models.SlugField(help_text='Identificador únic per a URLs', max_length=150, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('historical_period', models.CharField(blank=True, help_text='Historical era of the story (e.g. Iberian, Roman, Medieval, Modern)', max_length=100, verbose_name='Historical Period')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude in decimal degrees (-90 to 90)', null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, help_text='Longitude in decimal degrees (-180 to 180)', null=True, verbose_name='Longitude')),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes', verbose_name='Reading Time')),
                ('difficulty', models.CharField(default='easy', help_text='Difficulty level (e.g. easy, medium, hard)', max_length=50, verbose_name='Difficulty')),
                ('attachments', models.ManyToManyField(blank=True, help_text='Document attachments linked to this story.', related_name='attached_to_stories', to='media_files.documentfile', verbose_name='Attachments')),
                ('category', models.ForeignKey(blank=True, help_text='Category for this story (defaults to Storytelling category)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='core.category', verbose_name='Category')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per')),
                ('featured_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_stories', to='media_files.imagefile', verbose_name='Featured media')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ('slug', 'id'),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StoryCategorySingleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(help_text='Root category for all stories', on_delete=django.db.models.deletion.PROTECT, related_name='story_singleton', to='core.category', verbose_name='Storytelling Category')),
            ],
            options={
                'verbose_name': 'Storytelling Category Configuration',
            },
        ),
        migrations.CreateModel(
            name='StoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('audio_transcript', models.TextField(blank=True, verbose_name='Audio Transcript')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='storytelling.story')),
            ],
            options={
                'verbose_name': 'Story Translation',
                'db_table': 'storytelling_story_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
