# Generated by Django 5.2.8 on 2026-05-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='source_name',
            field=models.CharField(blank=True, help_text="Name of the source (e.g. 'Ajuntament de Cabrera de Mar', 'Museu de Cabrera de Mar').", max_length=200, verbose_name='Source Name'),
        ),
        migrations.AddField(
            model_name='story',
            name='source_url',
            field=models.URLField(blank=True, help_text="Original URL of the source used for this story's content.", max_length=500, verbose_name='Source URL'),
        ),
    ]
