# Generated by Codex on 2026-06-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storytelling", "0002_add_source_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="story",
            name="longitude",
        ),
    ]
