# Generated by Django 5.2.8 on 2026-06-02 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0005_videofile_historicalvideofile'),
        ('storytelling', '0003_remove_story_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytranslation',
            name='audio_file',
            field=models.ForeignKey(blank=True, help_text='Manual audio guide recording for this language (falls back to TTS if empty)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories_audio', to='media_files.documentfile', verbose_name='Audio File'),
        ),
    ]
