# Generated by Django 5.2.8 on 2026-06-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0004_add_story_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storytranslation',
            name='audio_transcript',
        ),
    ]
