# Generated by Django 5.2.8 on 2025-12-08 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('mistral', 'Mistral AI'), ('groq', 'Groq')], default='openai', help_text='LLM provider to use for translations', max_length=20, verbose_name='Provider')),
                ('model_name', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gemini-2.0-flash-exp', 'Gemini 2.0 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('mistral-large-latest', 'Mistral Large'), ('llama-3.1-70b-versatile', 'Llama 3.1 70B')], default='gpt-4o-mini', help_text='Specific model to use for translations', max_length=50, verbose_name='Model Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether LLM translation is currently active', verbose_name='Active')),
                ('temperature', models.FloatField(default=0.3, help_text='Controls randomness in translations (0.0-2.0, lower is more deterministic)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Temperature')),
                ('max_tokens', models.PositiveIntegerField(default=2000, help_text='Maximum tokens for translation output', verbose_name='Max Tokens')),
            ],
            options={
                'verbose_name': 'LLM Provider Configuration',
            },
        ),
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('mistral', 'Mistral AI'), ('groq', 'Groq')], max_length=20, verbose_name='Provider')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model Name')),
                ('source_text', models.TextField(help_text='Original text that was translated', verbose_name='Source Text')),
                ('translated_text', models.TextField(help_text='Resulting translation', verbose_name='Translated Text')),
                ('source_language', models.CharField(help_text='Language code of source text', max_length=10, verbose_name='Source Language')),
                ('target_language', models.CharField(help_text='Language code of translated text', max_length=10, verbose_name='Target Language')),
                ('tokens_used', models.PositiveIntegerField(blank=True, help_text='Number of tokens consumed in the request', null=True, verbose_name='Tokens Used')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated cost in USD', max_digits=10, null=True, verbose_name='Cost Estimate')),
                ('success', models.BooleanField(default=True, help_text='Whether the translation was successful', verbose_name='Success')),
                ('error_message', models.TextField(blank=True, help_text='Error details if translation failed', verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Translation Log',
                'verbose_name_plural': 'Translation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
