# Generated by Django 5.2.8 on 2025-12-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gemini-2.0-flash-exp', 'Gemini 2.0 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('mistral-large-latest', 'Mistral Large'), ('llama-3.1-70b-versatile', 'Llama 3.1 70B'), ('llama3.2:latest', 'Llama 3.2 (Local)'), ('mistral:latest', 'Mistral 7B (Local)'), ('qwen2.5:latest', 'Qwen 2.5 (Local)'), ('gemma2:latest', 'Gemma 2 (Local)')], default='gpt-4o-mini', help_text='Specific model to use for translations', max_length=50, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('mistral', 'Mistral AI'), ('groq', 'Groq'), ('local', 'Local LLM (Ollama/LM Studio)')], default='openai', help_text='LLM provider to use for translations', max_length=20, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='translationlog',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('mistral', 'Mistral AI'), ('groq', 'Groq'), ('local', 'Local LLM (Ollama/LM Studio)')], max_length=20, verbose_name='Provider'),
        ),
    ]
