# Generated by Django 5.2.8 on 2025-12-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_translations", "0003_alter_llmproviderconfig_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmproviderconfig",
            name="anthropic_api_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional. Overrides LLM_ANTHROPIC_API_KEY env var.",
                verbose_name="Anthropic API Key",
            ),
        ),
        migrations.AddField(
            model_name="llmproviderconfig",
            name="gemini_api_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional. Overrides LLM_GEMINI_API_KEY env var.",
                verbose_name="Gemini API Key",
            ),
        ),
        migrations.AddField(
            model_name="llmproviderconfig",
            name="groq_api_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional. Overrides LLM_GROQ_API_KEY env var.",
                verbose_name="Groq API Key",
            ),
        ),
        migrations.AddField(
            model_name="llmproviderconfig",
            name="local_api_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional. Overrides LLM_LOCAL_API_URL env var.",
                verbose_name="Local API URL",
            ),
        ),
        migrations.AddField(
            model_name="llmproviderconfig",
            name="mistral_api_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional. Overrides LLM_MISTRAL_API_KEY env var.",
                verbose_name="Mistral API Key",
            ),
        ),
        migrations.AddField(
            model_name="llmproviderconfig",
            name="openai_api_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional. Overrides LLM_OPENAI_API_KEY env var.",
                verbose_name="OpenAI API Key",
            ),
        ),
    ]

