# Generated by Django 5.2.8 on 2026-02-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_translations', '0005_add_groq_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gemini-2.0-flash-exp', 'Gemini 2.0 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('mistral-large-latest', 'Mistral Large'), ('llama-3.3-70b-versatile', 'Llama 3.3 70B'), ('llama-3.1-8b-instant', 'Llama 3.1 8B Instant'), ('openai/gpt-oss-120b', 'GPT OSS 120B'), ('openai/gpt-oss-20b', 'GPT OSS 20B'), ('groq/compound', 'Groq Compound'), ('groq/compound-mini', 'Groq Compound Mini'), ('meta-llama/llama-4-maverick-17b-128e-instruct', 'Llama 4 Maverick 17B 128E (Preview)'), ('meta-llama/llama-4-scout-17b-16e-instruct', 'Llama 4 Scout 17B 16E (Preview)'), ('moonshotai/kimi-k2-instruct-0905', 'Kimi K2 Instruct 0905 (Preview)'), ('qwen/qwen3-32b', 'Qwen3 32B (Preview)'), ('llama3.2:latest', 'Llama 3.2 (Local)'), ('mistral:latest', 'Mistral 7B (Local)'), ('mistralai/mistral-nemo-instruct-2407', 'Mistral Nemo Instruct (Local)'), ('qwen2.5:latest', 'Qwen 2.5 (Local)'), ('gemma2:latest', 'Gemma 2 (Local)')], default='gpt-4o-mini', help_text='Specific model to use for translations', max_length=50, verbose_name='Model Name'),
        ),
    ]
