# Generated by Django 5.2.8 on 2026-05-28 17:31

from django.db import migrations, models


def configure_openrouter(apps, schema_editor):
    config_model = apps.get_model("llm_translations", "LLMProviderConfig")
    config_model.objects.update(
        provider="openrouter",
        model_name="openrouter/free",
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('llm_translations', '0006_alter_llmproviderconfig_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmproviderconfig',
            name='anthropic_api_key',
        ),
        migrations.RemoveField(
            model_name='llmproviderconfig',
            name='groq_api_key',
        ),
        migrations.RemoveField(
            model_name='llmproviderconfig',
            name='local_api_url',
        ),
        migrations.RemoveField(
            model_name='llmproviderconfig',
            name='mistral_api_key',
        ),
        migrations.RemoveField(
            model_name='llmproviderconfig',
            name='openai_api_key',
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='openrouter_api_key',
            field=models.TextField(blank=True, default='', help_text='Optional. Overrides LLM_OPENROUTER_API_KEY env var.', verbose_name='OpenRouter API Key'),
        ),
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='model_name',
            field=models.CharField(choices=[('openrouter/free', 'OpenRouter Free'), ('gemini-2.0-flash-exp', 'Gemini 2.0 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro')], default='openrouter/free', help_text='Specific model to use for translations', max_length=50, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter'), ('gemini', 'Google Gemini')], default='openrouter', help_text='LLM provider to use for translations', max_length=20, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='translationlog',
            name='provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter'), ('gemini', 'Google Gemini')], max_length=20, verbose_name='Provider'),
        ),
        migrations.RunPython(configure_openrouter, migrations.RunPython.noop),
    ]
