# Generated by Django 5.2.8 on 2025-12-11 00:00

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("media_files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Data de creacio",
                        verbose_name="Data de creacio",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data de modificacio",
                        verbose_name="Data de modificacio",
                    ),
                ),
                (
                    "metatitulo",
                    models.CharField(
                        blank=True,
                        help_text="Metatitol per a SEO",
                        max_length=255,
                        null=True,
                        verbose_name="Metatitol",
                    ),
                ),
                (
                    "metadescripcion",
                    models.TextField(
                        blank=True,
                        help_text="Metadescripcio per a SEO",
                        null=True,
                        verbose_name="Metadescripcio",
                    ),
                ),
                ("slug", models.SlugField(help_text="Identificador unic per a URLs", max_length=150, unique=True, verbose_name="Slug")),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("info_point", "Punt d'informacio"),
                            ("privacy", "Política de privacitat"),
                            ("legal_notice", "Avis legal"),
                            ("cookies", "Política de cookies"),
                            ("contact", "Contacte"),
                            ("inclusion", "Diversitat i inclusio"),
                        ],
                        help_text="Tipus de plantilla predefinida (unica per pagina)",
                        max_length=50,
                        unique=True,
                        verbose_name="Template",
                    ),
                ),
                ("is_published", models.BooleanField(default=True, verbose_name="Publicado")),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuari que va crear el registre",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creat per",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Ultim usuari que va modificar el registre",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificat per",
                    ),
                ),
                (
                    "featured_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="static_pages_featured",
                        to="media_files.imagefile",
                        verbose_name="Imagen destacada",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="static_pages_attachment",
                        to="media_files.documentfile",
                        verbose_name="Documento adjunto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Static Page",
                "verbose_name_plural": "Static Pages",
                "ordering": ("slug",),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StaticPageTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("titulo", models.CharField(max_length=200, verbose_name="Titol")),
                ("cuerpo", models.TextField(blank=True, verbose_name="Cos")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="static_pages.staticpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Static Page Translation",
                "db_table": "static_pages_staticpage_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
