# Generated by Django 5.2.8 on 2025-12-11 03:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='metadescripcion',
            field=models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='metatitulo',
            field=models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(help_text='Identificador únic per a URLs', max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='template',
            field=models.CharField(choices=[('info_point', "Punt d'informació"), ('privacy', 'Política de privacitat'), ('legal_notice', 'Avís legal'), ('cookies', 'Política de cookies'), ('contact', 'Contacte'), ('inclusion', 'Diversitat i inclusió')], help_text='Tipus de plantilla predefinida (única per pàgina)', max_length=50, unique=True, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='staticpagetranslation',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Títol'),
        ),
    ]
