# Generated by Django 5.2.8 on 2026-05-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_is_outdoor_alter_event_location_text'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcheckin',
            name='event_date',
            field=models.ForeignKey(blank=True, help_text='Specific session the user attended', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventdate'),
        ),
    ]
