# Generated by Django 5.2.8 on 2025-11-19 21:55

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='available_in_ca',
            field=models.BooleanField(default=True, verbose_name='Available in Catalan'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='available_in_en',
            field=models.BooleanField(default=True, verbose_name='Available in English'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='available_in_es',
            field=models.BooleanField(default=True, verbose_name='Available in Spanish'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='available_in_fr',
            field=models.BooleanField(default=True, verbose_name='Available in French'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='color',
            field=models.CharField(default='#000000', help_text='Hex color code, e.g., #FFFFFF', max_length=7, validators=[social.models.validator_hex], verbose_name='Color'),
        ),
    ]
