# Generated by Django 5.2.8 on 2025-11-19 23:46

import django.db.models.deletion
import simple_history.models
import social.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_sociallink_available_in_ca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSocialLink',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon_class', models.CharField(help_text="FontAwesome class, e.g., 'fa-brands fa-facebook'", max_length=50, verbose_name='Icon Class')),
                ('color', models.CharField(default='#000000', help_text='Hex color code, e.g., #FFFFFF', max_length=7, validators=[social.models.validator_hex], verbose_name='Color')),
                ('available_in_ca', models.BooleanField(default=True, verbose_name='Available in Catalan')),
                ('available_in_es', models.BooleanField(default=True, verbose_name='Available in Spanish')),
                ('available_in_en', models.BooleanField(default=True, verbose_name='Available in English')),
                ('available_in_fr', models.BooleanField(default=True, verbose_name='Available in French')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Social Link',
                'verbose_name_plural': 'historical Social Links',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
