import type { FeaturedEvent } from "./types";

export const SAMPLE_FEATURED_EVENTS: FeaturedEvent[] = [
  {
    id: "evt-festival-musica-verano-2025",
    title: "Cicle de concerts d’orgue",
    description: "Programa musical a l’església parroquial amb intèrprets convidats.",
    image_url: "/media/eventos/XXXVI_cicle_de_concerts_de_orgue.jpeg",
    starts_at: "2025-07-19T20:30:00+02:00",
    location: "Església parroquial, Cabrera de Mar",
    href: "#eventos",
  },
  {
    id: "evt-expo-arte-contemporaneo-2025",
    title: "Casa Trenc Alba: jornada de portes obertes",
    description: "Visita guiada per conèixer l’espai i la seva història recent.",
    image_url: "/media/eventos/casa_trenc_alba.jpeg",
    starts_at: "2025-09-06T11:00:00+02:00",
    location: "Casa Trenc Alba, Cabrera de Mar",
    href: "#eventos",
  },
  {
    id: "evt-mercado-producto-local-2025",
    title: "Fira de Nadal",
    description: "Paradetes, ambient familiar i activitats de temporada al centre del poble.",
    image_url: "/media/eventos/fira_nadal.jpg",
    starts_at: "2025-05-11T10:00:00+02:00",
    location: "Plaça del Poble, Cabrera de Mar",
    href: "#eventos",
  },
  {
    id: "evt-missatger-reis-2026",
    title: "Arribada del missatger dels Reis",
    description: "Recepció de cartes i animació familiar al centre del municipi.",
    image_url: "/media/eventos/missatger_reis.jpg",
    starts_at: "2026-01-03T18:00:00+01:00",
    location: "Plaça de l’Ajuntament, Cabrera de Mar",
    href: "#eventos",
  },
  {
    id: "evt-reforc-escolar-2025-2026",
    title: "Reforç escolar: inscripcions obertes",
    description: "Suport educatiu per al curs 2025–2026 (places limitades).",
    image_url: "/media/eventos/reforc_escolar_Curs_2025-2026.png",
    starts_at: "2025-09-15T17:30:00+02:00",
    location: "Biblioteca Municipal, Cabrera de Mar",
    href: "#eventos",
  },
  {
    id: "evt-concert-orgue-vespre-2025",
    title: "Concert d’orgue (vespre)",
    description: "Repertori clàssic amb interpretació comentada.",
    image_url: "/media/eventos/XXXVI_cicle_de_concerts_de_orgue.jpeg",
    starts_at: "2025-08-02T19:30:00+02:00",
    location: "Església parroquial, Cabrera de Mar",
    href: "#eventos",
  },
  {
    id: "evt-portes-obertes-trenc-alba-2025",
    title: "Casa Trenc Alba: visita guiada",
    description: "Recorregut pels espais i explicació del projecte patrimonial.",
    image_url: "/media/eventos/casa_trenc_alba.jpeg",
    starts_at: "2025-06-14T11:00:00+02:00",
    location: "Casa Trenc Alba, Cabrera de Mar",
    href: "#eventos",
  },
  {
    id: "evt-fira-nadal-tarda-2025",
    title: "Fira de Nadal: tarda familiar",
    description: "Tallers infantils, paradetes i música ambiental.",
    image_url: "/media/eventos/fira_nadal.jpg",
    starts_at: "2025-12-14T18:00:00+01:00",
    location: "Plaça del Poble, Cabrera de Mar",
    href: "#eventos",
  },
];
