# Generated by Django 5.2.8 on 2026-03-10 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeachSafetyAutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació')),
                ('trigger', models.CharField(choices=[('schedule', 'Schedule'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('window_key', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('weather_snapshot', models.JSONField(blank=True, default=dict)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per')),
            ],
            options={
                'verbose_name': 'Beach Safety Automation Run',
                'verbose_name_plural': 'Beach Safety Automation Runs',
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BeachSafetyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació')),
                ('published_status', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=20, verbose_name='Published status')),
                ('published_notes', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_beach_safety_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beach Safety Status',
                'verbose_name_plural': 'Beach Safety Status',
            },
        ),
        migrations.CreateModel(
            name='BeachSafetyProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació')),
                ('recommended_status', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=20)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('weather_snapshot', models.JSONField(blank=True, default=dict)),
                ('weather_source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation_window_start', models.DateTimeField()),
                ('recommendation_window_end', models.DateTimeField()),
                ('proposed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_beach_safety_proposals', to=settings.AUTH_USER_MODEL)),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='beach_safety.beachsafetyautomationrun')),
            ],
            options={
                'verbose_name': 'Beach Safety Proposal',
                'verbose_name_plural': 'Beach Safety Proposals',
                'ordering': ('-proposed_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('recommendation_window_start', 'recommendation_window_end'), name='unique_beach_safety_proposal_window')],
            },
        ),
    ]
