# Generated by Django 5.2.8 on 2026-03-10 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
        ('beach_safety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachsafetyproposal',
            name='source_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='automations.automationrun'),
        ),
        migrations.DeleteModel(
            name='BeachSafetyAutomationRun',
        ),
    ]
