# Generated by Django 5.2.8 on 2026-02-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_routes_festes_taxonomy'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for this news (defaults to News category)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news', to='core.category', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='NewsCategorySingleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(help_text='The root category for all news', on_delete=django.db.models.deletion.PROTECT, related_name='news_singleton', to='core.category', verbose_name='News Category')),
            ],
            options={
                'verbose_name': 'News Category Configuration',
            },
        ),
    ]
