# Generated by Django 5.2.8 on 2026-02-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0005_videofile_historicalvideofile'),
        ('news', '0002_add_category_and_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='attachments',
            field=models.ManyToManyField(blank=True, help_text='PDF documents and other files attached to this news', related_name='attached_to_news', to='media_files.documentfile', verbose_name='Attachments'),
        ),
    ]
