# Generated by Django 5.2.8 on 2026-02-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_add_attachments_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is featured'),
        ),
    ]
