import os
from pathlib import Path

import pytest
from django.core.exceptions import ValidationError
from django.core.files import File
from django.utils import timezone

from events.models import Event
from media_files.models import DocumentFile, ImageFile

pytestmark = pytest.mark.django_db


@pytest.fixture
def media_root(settings, tmp_path):
    settings.MEDIA_ROOT = tmp_path
    return tmp_path


@pytest.fixture
def sample_files_path() -> Path:
    return Path(__file__).resolve().parent / "files"


@pytest.fixture
def sample_document(sample_files_path) -> DocumentFile:
    pdf_path = sample_files_path / "sample.pdf"
    with pdf_path.open("rb") as source:
        return DocumentFile.objects.create(
            file=File(source, name=pdf_path.name),
            original_name=pdf_path.name,
            mime_type="application/pdf",
            size_bytes=os.path.getsize(pdf_path),
        )


@pytest.fixture
def sample_image(sample_files_path) -> ImageFile:
    image_path = sample_files_path / "sample.png"
    with image_path.open("rb") as source:
        return ImageFile.objects.create(
            file=File(source, name=image_path.name),
            original_name=image_path.name,
            mime_type="image/png",
            size_bytes=os.path.getsize(image_path),
        )


def test_create_event_basic(media_root):
    start = timezone.now()
    end = start + timezone.timedelta(hours=2)

    event = Event.objects.create(
        title="Concert",
        description="Live music in the park",
        start_at=start,
        end_at=end,
        is_published=True,
    )

    assert event.pk is not None
    assert event.slug.startswith("concert")
    assert event.safe_translation_getter("title", any_language=True) == "Concert"
    assert event.end_at == end


def test_end_before_start_raises_validation_error(media_root):
    start = timezone.now()
    end = start - timezone.timedelta(hours=1)

    with pytest.raises(ValidationError):
        Event.objects.create(
            title="Invalid",
            start_at=start,
            end_at=end,
        )


def test_slug_autogenerated_and_unique(media_root):
    start = timezone.now()
    event_one = Event.objects.create(title="Fiesta", start_at=start)
    event_two = Event.objects.create(title="Fiesta", start_at=start + timezone.timedelta(hours=1))

    assert event_one.slug == "fiesta"
    assert event_two.slug == "fiesta-2"


def test_is_future(media_root):
    future_event = Event.objects.create(
        title="Future Event",
        start_at=timezone.now() + timezone.timedelta(days=1),
    )
    past_event = Event.objects.create(
        title="Past Event",
        start_at=timezone.now() - timezone.timedelta(days=1),
    )

    assert future_event.is_future() is True
    assert past_event.is_future() is False


def test_event_can_attach_media(media_root, sample_document, sample_image):
    start = timezone.now() + timezone.timedelta(hours=3)

    event = Event.objects.create(
        title="Media Event",
        start_at=start,
        featured_media=sample_image,
    )
    event.attachments.add(sample_document)

    assert event.featured_media == sample_image
    assert event.attachments.count() == 1
