import os
from datetime import datetime, time
from pathlib import Path

import pytest
from django.core.exceptions import ValidationError
from django.core.files import File
from django.utils import timezone

from core.models import Category, Tag
from events.models import Event, EventCategorySingleton, EventDate
from media_files.models import DocumentFile, ImageFile

pytestmark = pytest.mark.django_db


@pytest.fixture
def media_root(settings, tmp_path):
    settings.MEDIA_ROOT = tmp_path
    return tmp_path


@pytest.fixture
def sample_files_path() -> Path:
    return Path(__file__).resolve().parent / "files"


@pytest.fixture
def events_category() -> Category:
    """Create the default events category."""
    category, _ = Category.objects.get_or_create(
        slug="events", defaults={"taxonomy": "events", "nombre": "Events"}
    )
    return category


@pytest.fixture
def events_singleton(events_category) -> EventCategorySingleton:
    """Create the events category singleton."""
    singleton, _ = EventCategorySingleton.objects.get_or_create(
        category=events_category
    )
    return singleton


@pytest.fixture
def sample_document(sample_files_path) -> DocumentFile:
    pdf_path = sample_files_path / "sample.pdf"
    if not pdf_path.exists():
        # Fallback for CI or missing files
        return DocumentFile.objects.create(original_name="test.pdf", size_bytes=100)
    with pdf_path.open("rb") as source:
        return DocumentFile.objects.create(
            file=File(source, name=pdf_path.name),
            original_name=pdf_path.name,
            mime_type="application/pdf",
            size_bytes=os.path.getsize(pdf_path),
        )


@pytest.fixture
def sample_image(sample_files_path) -> ImageFile:
    image_path = sample_files_path / "sample.png"
    if not image_path.exists():
        return ImageFile.objects.create(original_name="test.png", size_bytes=100)
    with image_path.open("rb") as source:
        return ImageFile.objects.create(
            file=File(source, name=image_path.name),
            original_name=image_path.name,
            mime_type="image/png",
            size_bytes=os.path.getsize(image_path),
        )


def test_create_event_basic(media_root, events_singleton):
    event = Event.objects.create(
        title="Concert",
        summary="Short summary",
        description="Live music in the park",
        is_published=True,
    )

    assert event.pk is not None
    assert event.slug.startswith("concert")
    assert event.safe_translation_getter("title", any_language=True) == "Concert"
    assert event.category == events_singleton.category


def test_create_event_with_dates(media_root, events_singleton):
    event = Event.objects.create(title="Multi-date")
    start1 = timezone.now() + timezone.timedelta(days=1)
    start2 = timezone.now() + timezone.timedelta(days=2)

    d1 = EventDate.objects.create(event=event, start_at=start1)
    d2 = EventDate.objects.create(event=event, start_at=start2)

    assert event.dates.count() == 2

    # Check that Event.start_at was updated by signal
    event.refresh_from_db()
    assert event.start_at == start1


def test_event_date_validation():
    event = Event.objects.create(title="Valid")
    start = timezone.now()
    end = start - timezone.timedelta(hours=1)

    date_obj = EventDate(event=event, start_at=start, end_at=end)
    with pytest.raises(ValidationError):
        date_obj.clean()


def test_slug_autogenerated_and_unique(media_root, events_singleton):
    event_one = Event.objects.create(title="Fiesta")
    event_two = Event.objects.create(title="Fiesta")

    assert event_one.slug == "fiesta"
    assert event_two.slug == "fiesta-2"


def test_is_future(media_root, events_singleton):
    future_event = Event.objects.create(title="Future")
    EventDate.objects.create(
        event=future_event, start_at=timezone.now() + timezone.timedelta(days=1)
    )

    past_event = Event.objects.create(title="Past")
    EventDate.objects.create(
        event=past_event, start_at=timezone.now() - timezone.timedelta(days=1)
    )

    assert future_event.is_future() is True
    assert past_event.is_future() is False


def test_event_can_attach_media(
    media_root, events_singleton, sample_document, sample_image
):
    event = Event.objects.create(
        title="Media Event",
        featured_media=sample_image,
    )
    event.attachments.add(sample_document)
    tag = Tag.objects.create(slug="music", nombre="Music")
    event.tags.add(tag)

    assert event.featured_media == sample_image
    assert event.attachments.count() == 1
    assert event.tags.count() == 1


def test_delete_event_date_updates_cache(events_singleton):
    start1 = timezone.now() + timezone.timedelta(days=1)
    start2 = timezone.now() + timezone.timedelta(days=2)

    event = Event.objects.create(title="Festival")
    d1 = EventDate.objects.create(event=event, start_at=start1)
    d2 = EventDate.objects.create(event=event, start_at=start2)

    # Initial state: nearest date is d1
    event.refresh_from_db()
    assert event.start_at == start1

    # Delete d1
    d1.delete()

    # Cache should update to d2
    event.refresh_from_db()
    assert event.start_at == start2


def test_past_event_fallback(events_singleton):
    """If all dates are past, cache should show the last one"""
    past1 = timezone.now() - timezone.timedelta(days=10)
    past2 = timezone.now() - timezone.timedelta(days=5)

    event = Event.objects.create(title="Past Event")
    EventDate.objects.create(event=event, start_at=past1)
    EventDate.objects.create(event=event, start_at=past2)

    event.refresh_from_db()
    event.update_cached_dates()
    event.refresh_from_db()

    # Should be the latest past date (past2)
    assert event.start_at == past2


def test_event_date_overlap_raises_error(events_singleton):
    """Test that overlapping sessions for the same event are rejected."""
    event = Event.objects.create(title="Overlap Test")
    start = timezone.now() + timezone.timedelta(days=1)
    end = start + timezone.timedelta(hours=2)

    # Create first session
    EventDate.objects.create(event=event, start_at=start, end_at=end)

    # Attempt to create overlapping session (starts during first)
    overlap_start = start + timezone.timedelta(hours=1)
    overlap_end = overlap_start + timezone.timedelta(hours=1)
    date_obj = EventDate(event=event, start_at=overlap_start, end_at=overlap_end)

    with pytest.raises(ValidationError):
        date_obj.clean()

    # Attempt to create overlapping session (ends during first)
    overlap_start2 = start - timezone.timedelta(hours=1)
    overlap_end2 = start + timezone.timedelta(minutes=30)
    date_obj2 = EventDate(event=event, start_at=overlap_start2, end_at=overlap_end2)

    with pytest.raises(ValidationError):
        date_obj2.clean()

    # Attempt to create overlapping session (encompasses first)
    overlap_start3 = start - timezone.timedelta(hours=1)
    overlap_end3 = end + timezone.timedelta(hours=1)
    date_obj3 = EventDate(event=event, start_at=overlap_start3, end_at=overlap_end3)

    with pytest.raises(ValidationError):
        date_obj3.clean()


def test_same_day_sessions_keep_earliest_start_cached(events_singleton):
    tz = timezone.get_current_timezone()
    target_day = (
        timezone.localtime(timezone.now(), tz) + timezone.timedelta(days=4)
    ).date()
    day_start = timezone.make_aware(datetime.combine(target_day, time.min), tz)

    event = Event.objects.create(title="Same Day Cache")
    first_session = EventDate.objects.create(
        event=event,
        start_at=day_start + timezone.timedelta(hours=9),
        end_at=day_start + timezone.timedelta(hours=10),
    )
    second_session = EventDate.objects.create(
        event=event,
        start_at=day_start + timezone.timedelta(hours=17),
        end_at=day_start + timezone.timedelta(hours=18),
    )

    event.refresh_from_db()
    assert event.start_at == first_session.start_at

    first_session.delete()
    event.refresh_from_db()
    assert event.start_at == second_session.start_at


def test_event_date_allows_touching_sessions_without_overlap(events_singleton):
    event = Event.objects.create(title="Touching Sessions")
    start = timezone.now().replace(microsecond=0) + timezone.timedelta(days=2)
    middle = start + timezone.timedelta(hours=2)
    end = middle + timezone.timedelta(hours=2)

    EventDate.objects.create(event=event, start_at=start, end_at=middle)

    non_overlapping = EventDate(event=event, start_at=middle, end_at=end)
    non_overlapping.clean()


def test_event_date_overlap_rejects_exact_duplicate_interval(events_singleton):
    event = Event.objects.create(title="Duplicate Interval")
    start = timezone.now().replace(microsecond=0) + timezone.timedelta(days=2)
    end = start + timezone.timedelta(hours=3)

    EventDate.objects.create(event=event, start_at=start, end_at=end)

    duplicate = EventDate(event=event, start_at=start, end_at=end)
    with pytest.raises(ValidationError):
        duplicate.clean()
