# Generated by Django 5.2.8 on 2025-11-26 17:01

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol')),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció')),
                ('slug', models.SlugField(help_text='Identificador únic per a la categoria', max_length=150, unique=True, verbose_name='Slug')),
                ('taxonomy', models.CharField(blank=True, help_text='Tipus de taxonomia (p.ex. theme, audience, season...)', max_length=50, verbose_name='Taxonomia')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('slug',),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació', verbose_name='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació', verbose_name='Data de modificació')),
                ('slug', models.SlugField(help_text="Identificador únic per a l'etiqueta", max_length=150, unique=True, verbose_name='Slug')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuari que va crear el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creat per')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, help_text='Últim usuari que va modificar el registre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificat per')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('slug',),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nombre', models.CharField(help_text='Nom de la categoria', max_length=150, verbose_name='Nom')),
                ('descripcion', models.TextField(blank=True, help_text='Descripció de la categoria', verbose_name='Descripció')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.category')),
            ],
            options={
                'verbose_name': 'Category Translation',
                'db_table': 'core_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nombre', models.CharField(help_text="Nom de l'etiqueta", max_length=100, verbose_name='Nom')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.tag')),
            ],
            options={
                'verbose_name': 'Tag Translation',
                'db_table': 'core_tag_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
