# Generated by Django 5.2.8 on 2025-12-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(
                blank=True,
                default='',
                help_text="Identificador d'icona per mostrar al front/back office",
                max_length=100,
                verbose_name='Icona',
            ),
        ),
    ]
