# Generated by Django 5.2.8 on 2025-12-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                help_text='Categoria pare (opcional)',
                null=True,
                on_delete=models.PROTECT,
                related_name='children',
                to='core.category',
                verbose_name='Pare',
            ),
        ),
    ]
