# Generated by Django 5.2.8 on 2026-02-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_category_parent"),
        ("media_files", "0005_videofile_historicalvideofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="featured_media",
            field=models.ForeignKey(
                blank=True,
                help_text="Imagen destacada para la categoria",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_in_categories",
                to="media_files.imagefile",
                verbose_name="Media destacada",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Si la categoria esta publicada",
                verbose_name="Publicada",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Documentos adjuntos de la categoria",
                related_name="attached_to_categories",
                to="media_files.documentfile",
                verbose_name="Adjuntos",
            ),
        ),
    ]
