# Generated by Django 5.2.8 on 2026-02-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_taxonomy_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='taxonomy',
            field=models.CharField(blank=True, choices=[('events', 'Eventos'), ('places', 'Lugares'), ('template', 'Plantilla'), ('theme', 'Tema'), ('audience', 'Audiencia'), ('season', 'Temporada'), ('news', 'Noticias'), ('other', 'Otro'), ('routes', 'Rutas'), ('festes', 'Festes Majors')], help_text='Tipus de taxonomia (p.ex. events, places, template...)', max_length=50, verbose_name='Taxonomia'),
        ),
    ]
