import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ThemeToggle } from "@/components/ThemeToggle";
import { ROUTES } from "@/lib/config/constants";
import { Activity, Server, ShieldCheck, ArrowRight, ExternalLink } from "lucide-react";
import { useHealthCheck } from "@/hooks/useHealthCheck";
/**
 * Landing Page - Entry point for the backoffice
 * Shows system status and provides quick access to login
 */
export function LandingPage() {
    const { backendStatus, dbStatus } = useHealthCheck();
    return (_jsxs("div", { className: "min-h-screen bg-muted/30 flex flex-col", children: [_jsx("header", { className: "mx-auto w-full max-w-6xl px-6 py-4", children: _jsxs("div", { className: "flex items-center justify-around", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("img", { src: "/assets/img/logo-cabrera-white.png", alt: "Gaudeix", className: "h-8 w-auto invert dark:invert-0" }), _jsxs("div", { children: [_jsx("h1", { className: "text-sm font-semibold", children: "Gaudeix" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Backoffice" })] })] }), _jsx(ThemeToggle, {})] }) }), _jsx("div", { className: "flex-1 flex items-center justify-center px-6", children: _jsxs("div", { className: "w-full max-w-4xl space-y-8", children: [_jsxs("div", { className: "text-center space-y-4", children: [_jsx("h2", { className: "text-3xl font-bold tracking-tight sm:text-4xl", children: "Panel de Administraci\u00F3n" }), _jsx("p", { className: "text-lg text-muted-foreground", children: "Sistema de gesti\u00F3n de contenido municipal" })] }), _jsxs("div", { className: "grid grid-cols-1 gap-4 md:grid-cols-3", children: [_jsxs(Card, { className: "border-border bg-card shadow-sm", children: [_jsxs(CardHeader, { className: "pb-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx(CardTitle, { className: "text-base", children: "Frontend" }), _jsx(Activity, { className: "h-5 w-5 text-green-500" })] }), _jsx(CardDescription, { className: "text-xs", children: "Sitio p\u00FAblico" })] }), _jsx(CardContent, { children: _jsx(Badge, { variant: "outline", className: "border-green-500/30 bg-green-500/10 text-green-700 dark:text-green-400", children: "Online" }) })] }), _jsxs(Card, { className: `border-border bg-card shadow-sm ${backendStatus === "online"
                                        ? ""
                                        : backendStatus === "checking"
                                            ? "border-yellow-500/30"
                                            : "border-red-500/30"}`, children: [_jsxs(CardHeader, { className: "pb-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx(CardTitle, { className: "text-base", children: "Backend" }), _jsx(Server, { className: `h-5 w-5 ${backendStatus === "online"
                                                                ? "text-green-500"
                                                                : backendStatus === "checking"
                                                                    ? "text-yellow-500"
                                                                    : "text-red-500"}` })] }), _jsx(CardDescription, { className: "text-xs", children: "API & Base de datos" })] }), _jsxs(CardContent, { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-muted-foreground", children: "API:" }), backendStatus === "checking" ? (_jsx(Badge, { variant: "outline", className: "border-yellow-500/30 bg-yellow-500/10 text-yellow-700 dark:text-yellow-400", children: "Verificando..." })) : backendStatus === "online" ? (_jsx(Badge, { variant: "outline", className: "border-green-500/30 bg-green-500/10 text-green-700 dark:text-green-400", children: "Online" })) : (_jsx(Badge, { variant: "outline", className: "border-red-500/30 bg-red-500/10 text-red-700 dark:text-red-400", children: "Offline" }))] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-muted-foreground", children: "Base de datos:" }), dbStatus === "ok" ? (_jsx("span", { className: "text-sm font-medium text-green-600 dark:text-green-400", children: "Conectada" })) : dbStatus === "error" ? (_jsx("span", { className: "text-sm font-medium text-red-600 dark:text-red-400", children: "Error" })) : (_jsx("span", { className: "text-sm text-muted-foreground", children: "-" }))] })] })] }), _jsxs(Card, { className: "border-border bg-card shadow-sm", children: [_jsxs(CardHeader, { className: "pb-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx(CardTitle, { className: "text-base", children: "Backoffice" }), _jsx(ShieldCheck, { className: "h-5 w-5 text-primary" })] }), _jsx(CardDescription, { className: "text-xs", children: "Panel administrativo" })] }), _jsx(CardContent, { children: _jsx(Badge, { variant: "outline", className: "border-primary/30 bg-primary/10 text-primary", children: "Activo" }) })] })] }), _jsxs("div", { className: "flex flex-col gap-3 sm:flex-row sm:justify-center sm:gap-4 pt-4", children: [_jsx(Button, { asChild: true, size: "lg", className: "group min-w-[200px]", children: _jsxs(Link, { to: ROUTES.LOGIN, children: [_jsx(ShieldCheck, { className: "mr-2 h-5 w-5" }), "Acceder al Backoffice", _jsx(ArrowRight, { className: "ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" })] }) }), _jsx(Button, { asChild: true, variant: "outline", size: "lg", className: "group min-w-[200px]", children: _jsxs("a", { href: "http://localhost:5173", target: "_blank", rel: "noopener noreferrer", children: [_jsx(ExternalLink, { className: "mr-2 h-5 w-5" }), "Ver Frontend P\u00FAblico"] }) })] })] }) }), _jsx("footer", { className: "border-t border-border/50 px-6 py-4", children: _jsx("p", { className: "text-center text-xs text-muted-foreground", children: "\u00A9 2025 Gaudeix Municipal \u00B7 Sistema de gesti\u00F3n" }) })] }));
}
